version: '3.4'

services:

  mariadb:
    container_name: mariadb
    image: pranayroot/mariadb:v1
    restart: always
    environment:
      MARIADB_USER: admin
      MARIADB_PASSWORD: 123 
      MARIADB_ROOT_PASSWORD: 123
    
  nginx:
    container_name: nginx
    image: pranayroot/nginx:v1
    restart: always
    ports:
      - 80

  php:
    container_name: php
    image: pranayroot/php:v1
    restart: always
    privileged: true 
    stdin_open: true
    command: bash