version: '3.4'

services:

  mariadb:
    container_name: mariadb
    image: pranayroot/mariadb:v1
    restart: always
    networks:
      - db-net
    environment:
      MARIADB_USER: admin
      MARIADB_PASSWORD: 123 
      MARIADB_ROOT_PASSWORD: 123
    ports:
      - 3306:3306
    
  nginx:
    container_name: nginx
    image: pranayroot/nginx:v1
    restart: always
    networks:
      - db-net
    privileged: true 
    stdin_open: true
    command: bash
    ports:
      - 80:80

  php:
    container_name: php
    image: pranayroot/php:v1
    restart: always
    networks:
      - db-net
    privileged: true 
    stdin_open: true
    command: bash


networks:
  db-net: {}