version: '3.4'

services:

  mariadb:
    container_name: mariadb
    image: pranayroot/mariadb:v1
    restart: always
    environment:
      MARIADB_USER: admin
      MARIADB_PASSWORD: 123 
      MARIADB_ROOT_PASSWORD: 123
    
  nginx:
    container_name: nginx
    image: pranayroot/nginx:v1
    restart: always