version: '3.4'

services:

  lemp:
    container_name: lemp
    image: pranayroot/lemp:v1
    restart: always
    networks:
      - db-net
    volumes: 
      - /home/ec2-user/rtcamp-assessment/WordPress:/var/www/localhost/htdocs
    ports:
      - 80:80
  


  mysql:
    container_name: mysql
    image: mysql:latest
    restart: always
    networks:
      - db-net
    environment:
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123 
      MYSQL_ROOT_PASSWORD: 123
    ports:
      - 3306:3306

#   nginx:
#     container_name: nginx
#     image: pranayroot/nginx:v1
#     restart: always
#     networks:
#       - db-net
#     privileged: true 
#     stdin_open: true
#     command: bash
#     ports:
#       - 80:80

#   php:
#     container_name: php
#     image: pranayroot/php:v1
#     restart: always
#     networks:
#       - db-net
#     privileged: true 
#     stdin_open: true
#     command: bash
#     ports:
#       - 9000:9000


networks:
  db-net: {}




