version: '3.5'

services:
  #databse
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_PASSWORD: 123
    networks:
      - db-net
  #php
  phpfpm:
    image: php:fpm
    depends_on:
      - db
    ports:
      - '9000:9000'
    volumes: ['/home/ec2-user/rtcamp-assessment/wordpress-docker/public:/usr/share/nginx/html']
    networks:
      - db-net
  #phpmyadmin
  # phpmyadmin:
  #   depends_on:
  #     - db
  #   image: phpmyadmin/phpmyadmin
  #   restart: always
  #   ports:
  #     - '8080:80'
  #   environment:
  #     PMA_HOST: db
  #     MYSQL_ROOT_PASSWORD: 123
  #   networks:
  #     - db-net
  #wordpress
  wordpress:
    depends_on: 
      - db
    image: wordpress:latest
    restart: always
    ports:
      - '8000:80'
    volumes: ['/home/ec2-user/rtcamp-assessment/wordpress-docker:/var/www/html']
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: 123
      WORDPRESS_DB_NAME: wordpress
    networks:
      - db-net
  #nginx
  proxy:
    image: nginx:1.17.10
    depends_on:
      - db
      - wordpress
    #  - phpmyadmin
      - phpfpm
    ports:
      - '8001:80'
    volumes: 
      - /home/ec2-user/rtcamp-assessment/wordpress-docker/:/var/www/html
      - /home/ec2-user/rtcamp-assessment/wordpress-docker/nginx/:/etc/nginx/
    networks:
      - db-net
networks:
  db-net: {}
volumes:
  db_data:
